# -*- coding: utf-8 -*-
"""Data_App_Table_croisement

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kr14p0fT3uHbrEeFPS_rb4Qss0o2aU-k
"""

import pandas as pd

df_final = pd.read_csv('/content/df_final.csv')
df_grouped = pd.read_csv('/content/df_panier_group.csv')
df_payments = pd.read_csv('/content/olist_order_payments_dataset.csv')
df_reviews = pd.read_csv('/content/olist_order_reviews_dataset.csv')

df_final

"""# **Nombre de commandes par client**

# Nombre de commande
"""

# Calculer le nombre d'occurrences de chaque customer_id dans df_final
customer_counts = df_final['customer_id'].value_counts().reset_index()

# Renommer les colonnes pour plus de clarté
customer_counts.columns = ['customer_id', 'orders_number']

# Afficher la table résultante
print(customer_counts)

"""# Etiquettes"""

# Définir les paliers
bins = [1, 2, 3, float('inf')]
labels = ['1', '2', '3+']

# Ajouter une colonne 'palier' au DataFrame en fonction de total_value
customer_counts['order_label'] = pd.cut(customer_counts['orders_number'], bins=bins, labels=labels, right=False)

customer_counts

customer_counts['order_label'].unique()

customer_counts

"""# **Table prix dépensé par le client**

# Prix total dépensé par client
"""

# Regroupement par customer_id et calcul de la somme du total_spent
basket_price = df_final.groupby('customer_id')['price'].sum().reset_index()
# Affichage du résultat
print(basket_price)

"""# Pallier de prix"""

# Définir les paliers
bins = [0, 50, 100, 150, float('inf')]
labels = ['Moins de 50', '50-99.99', '100-149.99', 'Plus de 150']

# Ajouter une colonne 'palier' au DataFrame en fonction de total_value
basket_price['palier'] = pd.cut(basket_price['price'], bins=bins, labels=labels, right=False)

basket_price

"""# **Table de croisement finale**"""

customer_counts

basket_price

df_croisement = pd.merge(customer_counts, basket_price, on='customer_id', how='left')
print(df_croisement)

"""# **TABLES FINALES**"""

df_croisement.to_csv('table_croisement.csv')

df_final = pd.merge(df_croisement, df_final, on='customer_id', how='left')

df_final

df_final.to_csv('final_v1.csv')

"""# **TABLE GROUPED**"""

df_grouped['customer_id'] = df_final['customer_id']
df_grouped['payment_type'] = df_final['payment_type']
df_grouped['review_score'] = df_final['review_score']
df_grouped['review_comment_message'] = df_final['review_comment_message']

df_grouped

df_croisement

df_grouped = pd.merge(df_grouped, df_croisement, on='customer_id', how='left')
df_grouped

df_grouped.to_csv('grouped_final_v1.csv')